### PR TITLE
Updated lib versions

### PR DESCRIPTION
**Pull request by riyadparvez**
- binutils 2.24
- latest STP revision
- removed dependencies ot-sanitise

### CODE REVIEW

**Comment by stefanbucur** [comment]
Thanks for the patch! Did you test the changes on any particular workloads, to confirm it properly works? I remember, for instance, that using the latest STP at some point was causing failed assertions in certain cases.

**Comment by riyadparvez** [comment]
I did test memcached running for a day in my laptop, I haven't seen any assertion violation. Also KLEE's experimental version has been using latest STP for a while. 

If you want, I can submit without the STP version modification.

BTW, do you have plan for maintaining Cloud9?

**Comment by stefanbucur** [comment]
Yes, splitting the patch in two would be best. Thanks!

Sorry for taking so long. Unfortunately, I won't have enough bandwidth in the foreseeable future to take care of Cloud9 as much as I wished.

**Comment by riyadparvez** [comment]
Closing this PR. New PR @ https://github.com/dslab-epfl/cloud9-depot/pull/3.

**Pull request closed without merging**
